# Generated by Django 5.0.6 on 2024-09-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmltext', models.TextField(verbose_name='Html for privacy policy')),
            ],
        ),
    ]
