# Generated by Django 5.0.6 on 2024-09-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_companyprivacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sponsor name')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='Sponsor logo')),
                ('info', models.TextField(verbose_name='Sponsor additional info')),
            ],
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Company logo'),
        ),
    ]
