# Generated by Django 5.0.6 on 2024-09-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_companysponsor_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.ImageField(null=True, upload_to='', verbose_name='Company certificate'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='promo_video',
            field=models.CharField(default='/', max_length=150, verbose_name='Promo video link'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisite',
            field=models.TextField(default='', verbose_name='Company requisites in html'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(verbose_name='Info about the company in html'),
        ),
    ]
