# Generated by Django 5.0.6 on 2024-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_companyinfo_certificate_companyinfo_promo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='promocode',
            field=models.CharField(default='', max_length=100, verbose_name='Promocode'),
        ),
    ]
