# Generated by Django 5.0.6 on 2024-09-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_review_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
