# Generated by Django 5.0.6 on 2024-09-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
