# Generated by Django 5.0.6 on 2024-09-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
