# Generated by Django 5.0.6 on 2024-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='teaser',
            field=models.TextField(default='', verbose_name='Short Teaser'),
        ),
    ]
