# Generated by Django 5.0.6 on 2024-10-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_faq_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybanner',
            name='url',
            field=models.TextField(null=True, verbose_name='Redirect url'),
        ),
    ]
