# Generated by Django 5.0.6 on 2024-10-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_companybanner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='slider_delay_in_millis',
            field=models.IntegerField(default=5000, verbose_name='Delay for image change in slider on main page'),
        ),
    ]
