# Generated by Django 5.0.6 on 2024-05-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Component name')),
                ('description', models.CharField(max_length=200, verbose_name='Component description')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Component name')),
                ('description', models.CharField(max_length=200, verbose_name='Component description')),
                ('serial', models.CharField(max_length=50, verbose_name='Component serial number')),
                ('component_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.componenttype')),
            ],
        ),
    ]
