# Generated by Django 5.0.6 on 2024-05-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='price_in_usd',
            field=models.FloatField(default=0, verbose_name='Component price in USD'),
        ),
    ]
