# Generated by Django 5.0.6 on 2024-05-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('description', models.CharField(max_length=200, verbose_name='Service description')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('description', models.CharField(max_length=200, verbose_name='Service description')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('description', models.CharField(max_length=200, verbose_name='Service description')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Service name')),
                ('serial', models.CharField(max_length=200, verbose_name='Serial number')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('experience_in_years', models.IntegerField(verbose_name='Work experience in years')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.masterspeciality')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('description', models.CharField(max_length=200, verbose_name='Service description')),
                ('base_price_in_usd', models.FloatField(verbose_name='Base service price in USD without parts')),
                ('device_types', models.ManyToManyField(to='service_app.devicetype')),
                ('service_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.servicetype')),
            ],
        ),
        migrations.AddField(
            model_name='masterspeciality',
            name='services',
            field=models.ManyToManyField(to='service_app.service'),
        ),
    ]
