# Generated by Django 5.0.6 on 2024-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Device type description'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Device type name'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Master name'),
        ),
        migrations.AlterField(
            model_name='masterspeciality',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Master speciality description'),
        ),
        migrations.AlterField(
            model_name='masterspeciality',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Master speciality name'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Service type name'),
        ),
    ]
