# Generated by Django 5.0.6 on 2024-09-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_alter_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Profile picture for master'),
        ),
    ]
