# Generated by Django 5.0.6 on 2024-10-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_master_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='phone_number',
            field=models.CharField(default='80291112233', max_length=15, verbose_name='Phone number'),
        ),
    ]
