# Generated by Django 5.0.6 on 2024-05-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0002_alter_device_name_alter_devicetype_description_and_more'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(verbose_name='Total price with all additions')),
                ('application_date', models.DateField(verbose_name='Date of order creation')),
                ('deadline_date', models.DateField(verbose_name='Deadline of order completion')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.device')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.devicetype')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.master')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_app.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.service')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.servicetype')),
            ],
        ),
    ]
