# Generated by Django 5.0.6 on 2024-05-15 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_alter_order_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 11, 36, 52, 441792), verbose_name='Deadline of order completion'),
        ),
    ]
