# Generated by Django 5.0.6 on 2024-05-15 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_alter_order_deadline_date'),
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='additional_components',
            field=models.ManyToManyField(to='master_app.component'),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='status',
            field=models.CharField(default='Awaiting acceptance', max_length=50, verbose_name='Order entry completion status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 18, 1, 24, 511957), verbose_name='Deadline of order completion'),
        ),
    ]
