# Generated by Django 5.0.6 on 2024-05-16 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_orderentry_additional_components_orderentry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 15, 39, 44, 674918), verbose_name='Deadline of order completion'),
        ),
    ]
