# Generated by Django 5.0.6 on 2024-05-16 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_alter_order_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 23, 17, 25, 200942), verbose_name='Deadline of order completion'),
        ),
    ]
