# Generated by Django 5.0.6 on 2024-09-09 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0016_alter_order_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 8, 22, 32, 33, 639508), verbose_name='Deadline of order completion'),
        ),
    ]
