# Generated by Django 5.0.6 on 2024-10-18 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0028_alter_order_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 17, 20, 20, 10, 958756), verbose_name='Deadline of order completion'),
        ),
    ]
