# Generated by Django 5.0.6 on 2024-05-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='passport_serial',
            field=models.CharField(max_length=50, verbose_name='User passport serial'),
        ),
    ]
