# Generated by Django 5.0.6 on 2024-05-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of the article')),
                ('cover', models.ImageField(upload_to='', verbose_name='Cover image for article')),
                ('author', models.CharField(max_length=50, verbose_name='Author name')),
                ('text', models.TextField(verbose_name='Full text of the article')),
                ('date', models.DateField(verbose_name='Date on which article was posted')),
            ],
        ),
    ]
