# Generated by Django 5.0.6 on 2024-05-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'News article', 'verbose_name_plural': 'News articles'},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='spoiler',
            field=models.CharField(default='default spoiler', max_length=200, verbose_name='Text for preview of the article'),
        ),
    ]
