# Generated by Django 5.0.6 on 2024-05-16 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0004_alter_master_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_in_years', models.IntegerField(default=0, verbose_name='Required experience in years')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.masterspeciality')),
            ],
        ),
    ]
